apiVersion: v1
kind: Service
metadata:
  name: jvm-service
  labels:
    app: jvm
spec:
  selector:
    app: jvm
  ports:
  - name: service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
status: 
  loadBalancer: {}